# Generated by Django 3.0.7 on 2020-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='data',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
